CREATE TABLE IF NOT EXISTS gb_blogfeed(
	PageID INT UNSIGNED NOT NULL,
	ID INT UNSIGNED NOT NULL,
	SetID INT UNSIGNED,
	LabelID INT UNSIGNED,
	language ENUM('ru') NOT NULL DEFAULT 'ru',
	published ENUM('Not published','Published') NOT NULL DEFAULT 'Not published',
	header VARCHAR(256) NOT NULL DEFAULT '', 
	subheader VARCHAR(1024) NOT NULL DEFAULT '', 
	preview VARCHAR(256),
	video VARCHAR(256),
	category VARCHAR(32) NOT NULL DEFAULT 'article',
	Ads ENUM('YES','NO') NOT NULL DEFAULT 'YES',
	UNIQUE(ID,language),
	PRIMARY KEY(PageID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (SetID) REFERENCES gb_media(SetID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (LabelID) REFERENCES gb_labels(LabelID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_blogcontent(
	PageID INT UNSIGNED NOT NULL,
	content BLOB,
	subtemplate VARCHAR(32) NOT NULL DEFAULT '',
	UserID INT UNSIGNED,
	PRIMARY KEY(PageID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (UserID) REFERENCES gb_staff(UserID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_amp(
	PageID INT UNSIGNED NOT NULL,
	content BLOB,
	PRIMARY KEY(PageID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_ina(
	PageID INT UNSIGNED NOT NULL,
	content BLOB,
	PRIMARY KEY(PageID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;