CREATE TABLE IF NOT EXISTS gb_redirects(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	hash CHAR(32) NOT NULL DEFAULT '',
	category VARCHAR(24) NOT NULL DEFAULT '',
	source VARCHAR(256) NOT NULL DEFAULT '',
	target VARCHAR(256) NOT NULL DEFAULT '',
	code ENUM('301','302') NOT NULL DEFAULT '301',
	PRIMARY KEY(ID),
	UNIQUE(hash),
	INDEX(category)
)ENGINE=InnoDB CHARACTER SET utf8;