CREATE TABLE IF NOT EXISTS gb_discounts(
	DiscountID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	caption VARCHAR(64) NOT NULL DEFAULT "",
	begining INT UNSIGNED NOT NULL DEFAULT 1,
	ended INT UNSIGNED NOT NULL DEFAULT 1,
	essence VARCHAR(1024) NOT NULL DEFAULT "",
	sticker VARCHAR(8) NOT NULL DEFAULT "",
	discount TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(DiscountID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_items(
	PageID INT UNSIGNED NOT NULL,
	ItemID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	DiscountID INT UNSIGNED,
	item VARCHAR(24) NOT NULL DEFAULT '',
	purchase DECIMAL(6,2) NOT NULL DEFAULT 0.00,
	selling DECIMAL(6,2) NOT NULL DEFAULT 0.00,
	dumping TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	outstock ENUM('not available','under the order') NOT NULL DEFAULT 'not available',
	PRIMARY KEY(ItemID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (DiscountID) REFERENCES gb_discounts(DiscountID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_models(
	PageID INT UNSIGNED NOT NULL,
	ItemID INT UNSIGNED,
	CategoryID INT UNSIGNED NOT NULL,
	RelCatID INT UNSIGNED,
	named VARCHAR(256) NOT NULL DEFAULT '',
	LabelID INT UNSIGNED,
	preview VARCHAR(256),
	mediaset VARCHAR(1024) NOT NULL DEFAULT '[]',
	subtemplate VARCHAR(32) NOT NULL DEFAULT '',
	status ENUM('available','not available') NOT NULL DEFAULT 'not available',
	currency ENUM('USD','EUR','UAH') NOT NULL DEFAULT 'USD',
	units  ENUM('шт.','м','м²','г.','кг.','л.') NOT NULL DEFAULT 'шт.',
	options VARCHAR(2048) NOT NULL DEFAULT '{}',
	description BLOB,
	PRIMARY KEY(PageID),
	UNIQUE(ModelID, language),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (ItemID) REFERENCES gb_items(ItemID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (CategoryID) REFERENCES gb_sitemap(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (RelCatID) REFERENCES gb_sitemap(PageID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (LabelID) REFERENCES gb_labels(LabelID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_filters(
	FilterID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	value VARCHAR(48) NOT NULL,
	caption VARCHAR(48) NOT NULL,
	UNIQUE(value)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS item_vs_filters(
	FilterID INT UNSIGNED NOT NULL,
	PageID INT UNSIGNED NOT NULL,
	PRIMARY KEY(FilterID,PageID),
	FOREIGN KEY (FilterID) REFERENCES gb_filters(FilterID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_stock(
	ItemID INT UNSIGNED NOT NULL,
	stock VARCHAR(24) NOT NULL DEFAULT 'main',
	remainder INT(4) UNSIGNED NOT NULL DEFAULT 0,
	FOREIGN KEY (ItemID) REFERENCES gb_items(ItemID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	INDEX(stock),
	UNIQUE(stock, ItemID)
)ENGINE=InnoDB CHARACTER SET utf8;

/***********************/

CREATE TABLE IF NOT EXISTS cb_things(
	ThingID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	votes INT(5) UNSIGNED NOT NULL DEFAULT 1,
	rating INT(5) UNSIGNED NOT NULL DEFAULT 4,
	type ENUM('page','category','showcase','post') NOT NULL DEFAULT 'page',
	created INT UNSIGNED NOT NULL DEFAULT 1,
	modified INT UNSIGNED NOT NULL DEFAULT 1,
	customizer VARCHAR(1024) NOT NULL DEFAULT '{}',
	PRIMARY KEY(ThingID)
)ENGINE=InnoDB CHARACTER SET utf8;

/***********************/

CREATE TABLE IF NOT EXISTS cb_materials(
	ThingID INT UNSIGNED NOT NULL,
	Material BLOB,
	Description VARCHAR(4096) NOT NULL DEFAULT '',
	PRIMARY KEY(ThingID),
	FOREIGN KEY (ThingID) REFERENCES cb_things(ThingID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_brands(
	BrandID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	idx CHAR(1) NOT NULL DEFAULT '',
	Name VARCHAR(32) NOT NULL DEFAULT '',
	link VARCHAR(32) NOT NULL DEFAULT '',
	logo VARCHAR(256),
	PRIMARY KEY(BrandID),
	UNIQUE(link),
	INDEX(idx)
)ENGINE=InnoDB CHARACTER SET utf8;

/***********************/

CREATE TABLE IF NOT EXISTS cb_discounts(
	DiscountID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	caption VARCHAR(64) NOT NULL DEFAULT "",
	essence VARCHAR(1024) NOT NULL DEFAULT "",
	sticker VARCHAR(8) NOT NULL DEFAULT "",
	discount TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(DiscountID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_sellers(
	SellerID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	SellerName VARCHAR(32) NOT NULL DEFAULT '',
	StoreName VARCHAR(32) NOT NULL DEFAULT '',
	PRIMARY KEY(SellerID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_categories(
	CatID INT UNSIGNED NOT NULL,
	ParentID INT UNSIGNED NOT NULL,
	DeID INT UNSIGNED NOT NULL,
	NameDE VARCHAR(64) NOT NULL DEFAULT '',
	NameEN VARCHAR(64) NOT NULL DEFAULT '',
	link VARCHAR(64) NOT NULL DEFAULT '',
	Level SMALLINT UNSIGNED NOT NULL,
	BranchID INT UNSIGNED,
	status ENUM('enabled','disabled') NOT NULL DEFAULT 'enabled',
	delivery_price INT(4) UNSIGNED NOT NULL DEFAULT 40,
	BranchID INT UNSIGNED,
	favorite INT(1) UNSIGNED
	PRIMARY KEY(CatID),
	INDEX(RelID),
	INDEX favorites(favorite)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_subitems(
	ItemID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ThingID INT UNSIGNED NOT NULL,
	DiscountID INT UNSIGNED,
	SubName VARCHAR(24) NOT NULL DEFAULT '',

	Cost DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	Price DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	Currency ENUM('EUR','USD','GBP','UAH') NOT NULL DEFAULT 'GBP',
	Units ENUM('pcs.','m','m²','g.','kg.','l.') NOT NULL DEFAULT 'pcs.',
	PRIMARY KEY(ItemID),
	FOREIGN KEY (ThingID) REFERENCES cb_things(ThingID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (DiscountID) REFERENCES cb_discounts(DiscountID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_items(
	ThingID INT UNSIGNED NOT NULL,
	ItemID INT UNSIGNED,
	SellerID INT UNSIGNED NOT NULL,
	RefID BIGINT UNSIGNED,
	CatID INT UNSIGNED NOT NULL,
	Status ENUM('available','not available','new','sold','deleted') NOT NULL DEFAULT 'not available',

	BrandID INT UNSIGNED,
	Named VARCHAR(256) NOT NULL DEFAULT '',
	Preview VARCHAR(256),
	State VARCHAR(42) NOT NULL DEFAULT '',
	PRIMARY KEY(ThingID),
	UNIQUE(RefID),
	FOREIGN KEY (ThingID) REFERENCES cb_things(ThingID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (ItemID) REFERENCES cb_subitems(ItemID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (CatID) REFERENCES cb_categories(CatID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (SellerID) REFERENCES cb_sellers(SellerID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (BrandID) REFERENCES cb_brands(BrandID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cb_item_extended(
	ThingID INT UNSIGNED NOT NULL,
	Mediaset JSON,
	Subtemplate VARCHAR(32) NOT NULL DEFAULT 'default',
	DescID INT UNSIGNED,
	Options VARCHAR(1024) NOT NULL DEFAULT '{}',
	Compatibility VARCHAR(2048) NOT NULL DEFAULT '{}',
	PRIMARY KEY(ThingID),
	FOREIGN KEY (ThingID) REFERENCES cb_items(ThingID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (DescID) REFERENCES cb_materials(ThingID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;