CREATE TABLE IF NOT EXISTS gb_lineups(
	LineID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	LabelID INT UNSIGNED NOT NULL,
	Lineup VARCHAR(24) NOT NULL DEFAULT "",
	Model VARCHAR(32) NOT NULL DEFAULT "",
	image VARCHAR(256) NOT NULL DEFAULT "/images/vehicle.png",
	last_update INT UNSIGNED NOT NULL DEFAULT 0,
	published ENUM('Not Published','Published') NOT NULL DEFAULT 'Published',
	PRIMARY KEY(LineID),
	UNIQUE(LabelID,Lineup,Model),
	FOREIGN KEY (LabelID) REFERENCES gb_labels(LabelID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_parts(
	PartID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	RefID INT UNSIGNED NOT NULL,
	CatID INT UNSIGNED NOT NULL,
	LineID INT UNSIGNED NOT NULL,
	Reference VARCHAR(128) NOT NULL DEFAULT "n/a",
	named VARCHAR(256) NOT NULL DEFAULT "n/a",
	preview VARCHAR(256) NOT NULL DEFAULT "",
	price DECIMAL(6,2),
	added INT UNSIGNED NOT NULL DEFAULT 0,
	imageset VARCHAR(2048) NOT NULL DEFAULT '[]',
	optionset VARCHAR(1024) NOT NULL DEFAULT '{}',

	PRIMARY KEY(PartID),
	UNIQUE(RefID),
	FOREIGN KEY (CatID) REFERENCES gb_categories(CatID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (LineID) REFERENCES gb_lineups(LineID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_categories(
	CatID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PageID INT UNSIGNED NOT NULL DEFAULT 0,
	indx CHAR(1) NOT NULL DEFAULT '',
	category VARCHAR(64) NOT NULL DEFAULT "n/a",
	alias VARCHAR(64) NOT NULL DEFAULT "n/a",
	PRIMARY KEY(CatID),
	INDEX(indx),
	UNIQUE(category),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)ENGINE=InnoDB CHARACTER SET utf8;

/*INSERT INTO gb_categories (category,indx) VALUES (SELECT category,indx FROM gb_parts FROUP BY category)*/