CREATE TABLE IF NOT EXISTS cb_brands(
	BrandID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	brand VARCHAR(32) NOT NULL DEFAULT '',
	idx CHAR(1) NOT NULL DEFAULT '',
	slug VARCHAR(32) NOT NULL DEFAULT '',
	logo VARCHAR(256),
	favorite INT(1) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(BrandID),
	UNIQUE(slug),
	INDEX(favorite),
	INDEX(idx)
)ENGINE=InnoDB CHARACTER SET utf8;