CREATE TABLE IF NOT EXISTS gb_media(
	SetID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	language ENUM('ru') NOT NULL DEFAULT 'ru',
	Category VARCHAR(32) NOT NULL DEFAULT '',
	Name VARCHAR(32) NOT NULL DEFAULT '',
	Mediaset TEXT,
	PRIMARY KEY(SetID),
	UNIQUE(language,Category,Name)
)ENGINE=InnoDB CHARACTER SET utf8;